dofile("tests/mock_wow.lua")
for _,file in ipairs({"Constants.lua","Database.lua","ICCSession.lua","Core.lua","Roster.lua","Roles.lua","SkadaAdapter.lua","Segments.lua","Damage.lua","BQL.lua","Optimizer.lua","BPC.lua","PlanBundle.lua","Encounter.lua","Export.lua","UI.lua","Commands.lua"}) do dofile(file) end
dofile("tests/test_skada.lua")
dofile("tests/test_roles.lua")
dofile("tests/test_roster_snapshot.lua")
dofile("tests/test_history.lua")
dofile("tests/test_plan_bundle.lua")
dofile("tests/test_safe_loading.lua")
dofile("tests/test_icc_session.lua")
dofile("tests/test_optimizer.lua")
dofile("tests/test_damage.lua")
dofile("tests/test_encounter.lua")
dofile("tests/test_bql.lua")
dofile("tests/test_bql_25.lua")
dofile("tests/test_bpc.lua")
dofile("tests/test_export.lua")
dofile("tests/test_worksheet_export.lua")
dofile("tests/test_commands.lua")
dofile("tests/test_ui.lua")
print("PizzaRaidPlanner tests: PASS")
